### PR TITLE
Translated derp_strings.xml into Arabic

### PR DESCRIPTION
**Pull request by abadawe-dev**
Added Arabic translation (again).

### CODE REVIEW

**Review by NurKeinNeid — CHANGES_REQUESTED** [review]
It fails to compile

**Comment by abadawe-dev** [comment]
> It fails to compile

What is the error message?

**Comment by NurKeinNeid** [comment]
packages/apps/DerpLauncher/res/values-ar/derp_strings.xml:0: error: xml parser error: not well-formed (invalid token).
packages/apps/DerpLauncher/res/values-ar/derp_strings.xml: error: file failed to compile.

**Comment by abadawe-dev** [comment]
@NurKeinNeid try now it should work and sorry for the inconvenience.

**Comment by NurKeinNeid** [comment]
Thanks for your contributions! It works now and is merged: https://github.com/DerpFest-12/packages_apps_DerpLauncher/commit/228fe48244f7657a5d5b3d142c584c9e43febc50

**Pull request closed without merging**
